version: "3"

networks:
  network:
    driver: "bridge"

services:
  nginx:
    build:
      context: "."
      dockerfile: "nginx.dockerfile"
    networks:
      - "network"
    ports:
      - "80:80"
      - "443:443"
  aws:
    image: "localstack/localstack:0.11.2"
    networks:
      - "network"
    ports:
      - "4566:4566"
      - "4571:4571"
    volumes:
      - "./.aws:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      SERVICES: "s3"
      DATA_DIR: "/tmp/localstack/data"
      HOST_TMP_FOLDER: "./.aws"
      DEBUG: "true"

  imgproxy:
    image: "darthsim/imgproxy:v2"
    networks:
      - "network"
    ports:
      - "8080:8080"
    env_file:
      - "./.env"
    tty: true
