version: "3"

networks:
  network:
    driver: "bridge"

services:
  nginx:
    build:
      context: "."
      dockerfile: "nginx.dockerfile"
    networks:
      - "network"
    ports:
      - "80:80"
      - "443:443"
